# Site settings
title: Étienne Michon's website
description: ""
url: "http://etiennem.github.io/"
baseurl: ""
timezone: Europe/Paris
encoding: utf-8
#defaults:
#	-
#		scope:
#			path: "" # an empty string here means all files in the project
#		values:
#			layout: "default"
#			author: "Étienne Michon"

# Sheekyll settings
logoUrl: http://placehold.it/160
email: etienne.michon@riseup.net
homeArticle: 5

# Build settings
markdown: kramdown
permalink: pretty
